name: CI - Pipeline Alberto Caballero
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Pruebas de SAST
          run: echo "Pruebas de SAST"

        - name: Create file with credentials
          run: |
            echo "[credentials]" > credentials.ini
            echo "username = ${{ secrets.USERNAME }}" >> credentials.ini
            echo "password = ${{ secrets.PASSWORD }}" >> credentials.ini
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build docker image
          run: |
            docker build -t devops-ws:$(date +%s) .